### ISSUE TITLE
Frequent Bad Gateway Error

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#1567]
Since 2 or 3 days I most often have:
```
5xx: Server Error
This doesn't happen often, but it looks like something is broken. Hitting the back button and trying again might be your best bet. If that doesn't work you can head back to the homepage.

There might be more information on our status page.

Additional Details:
Bad gateway
The web server reported a bad gateway error.

Ray ID: 4598d2af0dd93be7
Your IP address: 
Error reference number: 502
Cloudflare Location: Paris
```
or I am regularly logged out.

**Comment by Len512** [comment]
Same thing happening to me for over a month now...

**Comment by Eauheni** [comment]
Looks like there was a server error! (500)

We have taken note of the situation and will be looking into it.

If you would like to supply us with some details as to how this happened please visit our Github issues list. This will help us get things fixed faster.

**Comment by asevos** [comment]
Site is working very slow, get server error all the time. Sometimes it is bearable, and sometimes it makes any action impossible.

**Comment by kazk** [comment]
Sorry about this. There were more frequent downtimes recently after we did some maintenance.
I've deployed some fix on Friday and it's looking better than the past few weeks. Still monitoring to see if it can handle the busiest days.

The slowness is not a new issue unfortunately. We can't make Codewars faster right now, but I'm going to be taking over the project soon and will start working on improving the experience. We didn't have anyone working on it for the past 2 years or so and it hasn't scaled well to handle the increased number of users.

**Comment by jarv3r** [comment]
Same error here:

`Looks like there was a server error! (500)
We have taken note of the situation and will be looking into it.

If you would like to supply us with some details as to how this happened please visit our Github issues list. This will help us get things fixed faster.

The operation: #<Moped::Protocol::Command @length=58 @request_id=13277 @response_to=0 @op_code=2004 @flags=[] @full_collection_name="admin.$cmd" @skip=0 @limit=-1 @selector={:ismaster=>1} @fields=nil> failed with error nil`

**Comment by kazk** [comment]
Thanks for reporting @jarv3r.
That's a separate issue caused by some database operation failing. It's been happening for the past few years as far as I know and have been reported multiple times.

**Comment by kazk** [comment]
Closing because "Bad Gateway" error is not happening frequently anymore.

**Comment by Len512** [comment]
The problem is still there and I dare say even worse... During the past week I am constantly disconnected at random times or I get the error I posted above at least once a day...

**Comment by kazk** [comment]
@Len512 Can you describe how you're getting the bad gateway error? Is it completely random? What causes the error most frequently? Some things are simply too slow when busy. It might give us a better idea.

> I dare say even worse

According to the monitoring service, it's been at least better than the past 3 months.

Note that Codewars has been embarrassingly slow and these server errors does happen when it's busy (this is not new). The issue was that the frequency was unusually high even in Codewars' standards.

**Comment by Len512** [comment]
It mostly happens when I submit a solution or refresh the list of unsolved katas. 
I use filters for the kata search, for example: 
`/search/javascript?q=&r[]=-8&r[]=-7&r[]=-6&r[]=-5&xids=played&order_by=total_completed+desc`

I encountered this already twice today (... and it's not even noon here ;) )

The disconnection problem occurs usually right after the 502 error, though it has happened at completely random times as well (which is normal I guess, depending on the traffic).

**Comment by kazk** [comment]
Thanks @Len512! Can you clarify some points?

> When I submit a solution

Is this when you "finalize" the solution?

> and it's not even noon here ;)

What's your time zone? We have more traffic during 2AM-12PM PST, peak is around 6-7 AM PST (this makes it difficult for us to experience the worst Codewars).

> The disconnection problem occurs usually right after the 502 error

Can you elaborate on "disconnection problem"? Do you mean you're getting logged out?

**Comment by g964** [comment]
Today I have been logged out many times (at PST time between 0:00 and 09:00) + "Retry for a live version" + the "PUBLISH" button most often doesn't appear when I "SAVE" (trying to publish a translation). At that moment my PST time is 11:10.

**Comment by kazk** [comment]
@g964 

> Retry for a live version" + the "PUBLISH" button most often doesn't appear when I "SAVE" (trying to publish a translation).

Can you post a screenshot on #1575? It'll help me understand the problem better.

**Comment by Len512** [comment]
> Is this when you "finalize" the solution?
Yes, clicking the "Submit button" to finalise/submit my final solution.
> What's your time zone?
It's UTC/GMT +2 hours (CEST)
> Do you mean you're getting logged out?
Yes, sometimes I am getting logged out after submitting my final solution / refreshing the list of katas.

**Comment by kazk** [comment]
I've increased the timeout of the load balancer. This should reduce the bad gateway error from slowness.

**Comment by Len512** [comment]
No server error today, looks like things are going smoothly so far. Thanks for your efforts, @kazk !

**Comment by kazk** [comment]
Thanks for letting me know @Len512. We need to fix the root cause (terrible performance), but I'm glad it's better.

**Comment by NabilotexD** [comment]
Hey, today I discovered codewars and tried to sign up, but the same 'bad gateway' error is happening when I press enlist (I have passed the entry thing and entered my sign up data).

I would really like to sign up to the website, is there anything I can do?

<img width="915" alt="captura de pantalla 2018-10-12 a las 19 11 06" src="https://user-images.githubusercontent.com/43793541/46883554-b7238a80-ce52-11e8-958b-a10adb7678ef.png">

**Comment by kazk** [comment]
@NabilotexD Sorry about that. That's a separate issue. Signup has been extremely slow and it often timeouts. https://github.com/Codewars/codewars.com/issues/1516

**Comment by NabilotexD** [comment]
Don't worry, I fixed it, thx anyways

**Comment by asdf334** [comment]
Apparently constantly clicking what you wanna do makes it go faster. dunno why, but it does
