### ISSUE TITLE
Completed kata still being reported as not completed in kata detail page

### ISSUE THREAD

**Issue by ZEDCWT** [Codewars/codewars.com#1683]
#### Describe the bug
So i just completed [this kata](https://www.codewars.com/kata/5c374b346a5d0f77af500a5a), (more exactly, i clicked `submit my solution`). And suddenly redirected to the solutions page as usual but seeing
![20190116212400](https://user-images.githubusercontent.com/7867810/51251790-130f2980-19d5-11e9-937c-ec30bc595aad.png)

The 4 point honor was added (39888 -> 39892), and it is both reported as completed on /{user}/completed page and /kata list page
![20190116212451](https://user-images.githubusercontent.com/7867810/51251873-49e53f80-19d5-11e9-942a-452fe4a0ea31.png)
![20190116212501](https://user-images.githubusercontent.com/7867810/51251875-4a7dd600-19d5-11e9-9903-18806d9fcb24.png)

But not on the kata detail page or trainning page
![20190116212613](https://user-images.githubusercontent.com/7867810/51251922-6aad9500-19d5-11e9-8766-5cf3641eb9e6.png)
![20190116212622](https://user-images.githubusercontent.com/7867810/51251923-6b462b80-19d5-11e9-8c62-18a9c9f7827a.png)

To clearify, im the only one completed it so far.
And i was not logged out during the whole process.

PS. I will not submit again before someone can investigate it.

**Comment by FArekkusu** [comment]
Happened to me a few times as well on Beta katas exclusively. I didn't report this as the behavior of this bug is identical to #1592:
* the user is redirected to still "closed" solutions page, and the "previous solutions" tab is absent in the trainer
* the honor is granted, the kata is listed as completed in the user's profile, and the solution is stored in the user's profile as well.

**Comment by hobovsky** [comment]
The same happened to me with an old kata, so it's rather not an issue with betas: [Explosive Sum](https://www.codewars.com/kata/52ec24228a515e620b0005ef). Solution is listed in my profile, points and progress are rewarded correctly, just kata details page does not recognize it as solved ("Train" and not "Train Again", cannot view solutions, etc).

I solved a JavaScript version, but details page for another JS kata I also finished today works fine.

**Comment by hobovsky** [comment]
I wanted to add random tests to [this kata](https://www.codewars.com/kata/are-the-brackets-balanced). I had to solve it first, so I submitted my Java solution, passed all the tests, and... solution is recorded, it is recognized by my profile, it is recognized by he kata as far as I can tell (all related counters increased), just kata page does not seem to acknowledge the fact. Cannot access solutions, cannot see test cases, cannot translate nor fork it.
Additionally, the issue with kata from previous post still persists after all these days, so I think it's not temporary/caching/timing thing.

**Comment by FArekkusu** [comment]
Unobvious work-around: re-submit your solution. You can also consider those 4 additional honor points for "completing the kata the 2nd time" as a bonus for having to deal with the DB issues ;)

___

At least that's the only way to gain access to the solutions page. What still remains unknown when this bug occurs:
* whether you can see `spoiler` comments after incorrectly registered completion
* whether the `+ ADD NEW` button is available when choosing the kata language

**Comment by beginnerJavaCoder** [comment]
I have the same trouble twice for today. I pushed my solutions 2 times, and system adds me honor for each push. It isn't problem of beta katas. I don't think this way is fair. But i also don't know how to see my solution in solutions' page and to vote up for solved kata.
![image](https://user-images.githubusercontent.com/32685534/51534849-5e578b00-1e60-11e9-81f2-aff1d91c58f6.png)
![image](https://user-images.githubusercontent.com/32685534/51535000-bf7f5e80-1e60-11e9-9026-6ebaec5d6ef1.png)

**Comment by kazk** [comment]
Sorry about this. I haven't spent much time on this yet.
It's been happening since 2016 (#311) but getting extra honor points might be new.

**Comment by FArekkusu** [comment]
> but getting extra honor points might be new

I mean you get kata-completion honor for both solution submissions, as according to the DB you've solved 2 different katas (if I iunderstood the situation correctly from your reply in #1592).

**Comment by hobovsky** [comment]
Exactly like @FArekkusu  says, everything is counted once per completion: I was able to vote twice, I got honor for solution, satisfaction and difficulty rating twice, I do not know about my rank progress, but I will be glad to test it with some purple :)

**Comment by FArekkusu** [comment]
> What still remains unknown when this bug occurs is:
> * whether you can see spoiler comments after incorrectly registered completion
> * whether the + ADD NEW button is available when choosing the kata language

Confirmed, when this bug occurs, you also can't write translations and see spoiler comments.

**Comment by eb110** [comment]
I have the same experience for following kata:
![image](https://user-images.githubusercontent.com/32197188/51622060-b27c7100-1f2d-11e9-865f-a06c2ad9d389.png)
![image](https://user-images.githubusercontent.com/32197188/51622072-bc05d900-1f2d-11e9-84c5-13270f8c8980.png)
![image](https://user-images.githubusercontent.com/32197188/51622081-c45e1400-1f2d-11e9-957e-93c73ccf0fad.png)

**Comment by eb110** [comment]
Same here:
![image](https://user-images.githubusercontent.com/32197188/51622142-e9eb1d80-1f2d-11e9-90e9-5799206978b9.png)
I've had to submit twice for java and javastring solutions

**Comment by hobovsky** [comment]
Small update on this one:

After clicking "Refactor" link under solution for such incorrectly registered kata, I get invalid editor screen, with blank language fields:

![cw error](https://user-images.githubusercontent.com/23709795/51632145-e1570f00-1f4e-11e9-8cc7-3c7194198a8d.png)

After completing such kata one more time, my overall rank score, language rank score, and totalCompleted counter are increased just as if I solved it the first time.

If I were to guess, it seems as if registering a solution was done in two separate code branches or maybe even transactions: one for user profile->solution, and one for kata->solution, and the second one for some reason either is not performed, or fails more and more often. Buy yeah, just a guess.

Feel free to delete my duplicated solutions, or all solutions for affected kata - I can always redo them.

**Comment by kazk** [comment]
@FArekkusu you're right. I don't think it's anything new. (There's so many issues that I get mixed up.) It might be happening more frequently though because of one change in the updated database driver.

---

I figured out the causes of these symptoms, but I'm still trying to find why/how it reaches to that point.

- Completed kata not marked as complete
  - Multiple records exists for a user with a kata. The code assumes there's only one record and it causes weird issues when incorrect one is returned.
  - See https://github.com/Codewars/codewars.com/issues/1592#issuecomment-441397283
  - Votes are associated with this document
- Solution not listed in kata's solution page
  - The solution failed to be grouped (including being in its own group)
  - I fixed a major data integrity issue yesterday that was causing this to happen very frequently so this shouldn't happen as often as before
- Solution on the profile's solution page is missing the link for "Discuss"
  - same reason as not listed under solutions
- Clicking "Refactor" for incorrect one results in empty editor
  - This is failing to look up the solution to be refactored because of multiple records

So the main cause of all of these is having multiple records for a user with a kata. And it's been like this for few years now :man_facepalming: 

After seeing all the data integrity issues, it's kind of amazing that it's still (mostly) working.

**Comment by Len512** [comment]
Not exactly the same issue, but I think it might be relevant: 
I have completed a kata, voted on it, it is in my profile under 'Solutions', I can see my solution under the solutions tab in the kata page, but it still shows up in my filtered search among the 'kata I have not completed' (1st pic).

![screen shot 2019-02-11 at 10 24 47](https://user-images.githubusercontent.com/25386785/52555373-cd822880-2de9-11e9-9c77-fc72c4c28cc3.png)
![screen shot 2019-02-11 at 10 27 23](https://user-images.githubusercontent.com/25386785/52555393-d8d55400-2de9-11e9-95ff-8b7aafd2c677.png)
![screen shot 2019-02-11 at 10 29 32](https://user-images.githubusercontent.com/25386785/52555404-e094f880-2de9-11e9-9ba8-90fc3ee92ec0.png)

**Comment by Voileexperiments** [comment]
This is happening for me too for [this kata](https://www.codewars.com/kata/theorem-proving-hello-world-prove-a-plus-0-equals-a-and-0-plus-a-equals-a/agda). I tried the kata back when it was beta and just completed it, however solutions are not unlocked.

It seems that when this happens, the saved solution associated with the kata is gone and the kata won't be displayed as solved.

**Comment by hobovsky** [comment]
It's not that solution is *completely* gone, usually there is some trace that it was accepted. For me, it's usually "Kata" tab in my profile - they always appear there for me, although on kata page I get no "train again" and solutions are hidden.

![image](https://user-images.githubusercontent.com/23709795/54419284-594be500-4707-11e9-9d72-c9abd761327d.png)


Yesterday hit the problem twice, and it happens to be more and more common. Or, at least, not as uncommon to be called just a 'glitch'. I noticed that incorrectly recorded solutions miss "Discuss" link in Profile/Solutions view, and there's quite a lot of these - I'd estimate it as 10% of all solutions do not have the link, so they are probably affected by this bug (and I have a scraper for these, so I can count exactly if someone wants). Quite a few.

![image](https://user-images.githubusercontent.com/23709795/54419594-235b3080-4708-11e9-92ec-cb5f69e672b4.png)


My question would be, when such situation is encountered, what should we do and what should not we do? After fix is done, will invalid solutions disappear or be fixed? Do we need to have at least one correctly recorded solution to make everything ok after the fix, or the incorrect ones will be fixed?

**Comment by Voileexperiments** [comment]
Indeed I'm seeing both of them:

![image](https://user-images.githubusercontent.com/14909989/54420252-7652d900-4744-11e9-9ff7-f37a92f793cf.png)

The problem is, the belong to the same project, but with a different session. The top one is

https://www.codewars.com/kata/projects/5c879f967aabc44ea5d7eefe/agda/session/5c8b5abba99b9c000d07d828

which is visible to me when I do a post request to it, while the bottom is

https://www.codewars.com/kata/projects/5c879f967aabc44ea5d7eefe/agda/session/5c879f985253b04f7f198347

which doesn't even return 403, it returns 404. So the session has completely disintegrated or something.

**Comment by Voileexperiments** [comment]
@kazk I recall a *long* time ago when there was a preview link to CW with the project interface (like the one in qualified.io?) that has the entire directory listing and several code editor blocks. Does it have to do with this?

**Comment by hobovsky** [comment]
Interesting follow-up: when issue creates two sets of solutions, I can choose into which set I submit solutions from now on. So when I accidentally got two Java solutions for one kata, I was able to submit Haskell solution twice too, once for each "set":

![image](https://user-images.githubusercontent.com/23709795/54433974-78f60400-472d-11e9-9c0f-34b6cfd25b2b.png)

It kinda sucks, because all numbers get really skewed then - I get honor, total progress and language progress counted as many times as there are "sets" :(

**Comment by kazk** [comment]
I'll try to explain what's going on in more detail expanding on https://github.com/Codewars/codewars.com/issues/1683#issuecomment-456951790.
This should also help me to organize my thoughts.  I might create a new issue later from this and pin it so I can point to it from the issue caused by this.

### Background

Codewars stores a `user`'s activities (progress, session, solutions, votes, etc) for a `code_challenge` (kata) in a document called `project`. So a `project` is **supposed to be the source of truth**. `project` has foreign keys `user_id` and `code_challenge_id` so Codewars can look up this information whenever needed. We have **19.6 million** `project`s.

`project` obviously **needs to be unique** to `(user_id, code_challenge_id)` and Codewars assumes this. A new `project` is only _supposed to be created_ when `project` with the same id pair doesn't already exist. But it's very unclear _when_ a `project` gets created because of the ORM's implicitness, and it seems like a new `project` is being created without this check in some conditions (I haven't figured this out yet). Also, this uniqueness is not enforced at the database level and therefore leaves some space for race conditions. This has been happening for at least few years and the frequency increased recently. The increased frequency is caused by either the database driver update or the increased number of users and `project`s.


### Problems

`project` is sometimes not unique and is causing all kinds of bugs.

**Completed kata not marked as complete**/**Withheld solutions after submit final**

Codewars checks if a `user` completed a kata by looking up the information in `project`.
This assumes that `project` is unique so the information can be wrong if a wrong `project` was returned.

```
{id: p1, user_id: u1, challenge_id: c1, completed: false}
{id: p2, user_id: u1, challenge_id: c1, completed: true}
```

The reason why multiple solutions show up in profile is that Codewars looks up all `project`s of a `user`.

**Clicking "Refactor" results in empty editor**

Failing to look up the correct `project` where the solution is embedded in.

```
{
  id: p1,
  user_id: u1,
  challenge_id: c1,
  languages: [
    {
      id: l1, 
      language_name: 'javascript',
      solutions: [{ id: s1, solution: 'some code' }]
    }
  ]
}
{
  id: p2,
  user_id: u1,
  challenge_id: c1
}
```

Finding `solution` `s1` fails when looking up the `project` for `challenge_id` and `user_id` returns the second one.

**Work in progress solution is gone after reopening trainer**

A different `project` was returned which doesn't contain the work in progress solution.


### Other Problems

We have some other issues that are often considered related to the issues mentioned above by the users.

**Solution not listed in kata's solution page**/**Missing "Discuss" link**

This is caused by the solution failing to be grouped (including being in its own group).
There was a major data integrity issue that was causing this to happen very frequently which I've fixed, but this is still happening in some unknown conditions.

**Not marked as completed in search result**

There's a separate list of completed kata ids that's being used for this and seems to get outdated sometimes.

---

@Voileexperiments

> The problem is, the belong to the same project, but with a different session.

No, you have two `project`s.
The first one belongs to `project` with id `5c879f967aabc44ea5d7eefe` and the second one belongs to `project` with id `5c879f96acf4894b0c349a1b`.

> @kazk I recall a long time ago when there was a preview link to CW with the project interface (like the one in qualified.io?) that has the entire directory listing and several code editor blocks. Does it have to do with this?

No, that was Jake's prototype UI and has nothing to do with Codewars.


@hobovsky

> It kinda sucks, because all numbers get really skewed then - I get honor, total progress and language progress counted as many times as there are "sets" :(

It sucks. I wish it was at least consistent like that.

**Comment by kazk** [comment]
@hobovsky 

> when such situation is encountered, what should we do and what should not we do?

Submitting multiple times can create duplicate solutions in multiple projects so it's not ideal, but I don't think it matters much at this point. The data is already really messed up over the past few years. We can't provide short term solution for this issue and users might be able to see others' solution or get honor points by doing it so I understand.

> After fix is done, will invalid solutions disappear or be fixed? Do we need to have at least one correctly recorded solution to make everything ok after the fix, or the incorrect ones will be fixed?

I still need to figure out the impact of this by analyzing 19.6 million documents before deciding what to do, but the highest priority will be obviously to preserve users' work. So we'll have at least one solution and maybe some extra if it's too difficult to determine. Other metadata like timestamps might be lost or altered. Again, I haven't decided how to approach this yet.

**Comment by Elmavis** [comment]
https://www.codewars.com/users/Elmavis
The same problem: #1779

**Comment by miread** [comment]
Just happened to me on an SQL kata

**Comment by marian316** [comment]
Happened to me on this kata - https://www.codewars.com/kata/who-likes-it/solutions/csharp
I'm able to see solutions and I have a "Train Again" button, but neither my solution is included in the list, nor the kata is marked as completed for me.

**Comment by AlexPutz** [comment]
Hello. I've experienced this bug. Today on 2 Katas I had following behaviour:
1. I type in solution, check with testcases.
2. Push an "Attempt" button, get honor and get a "solution" and a "kata solved mark in my profile".
3. Other users solutions are not unlocked, so I go to my profile, copy solution and re-submit.
4. Other users solutions are now opened, I get honor again and "get another kata solved".

In the past the solutions for the same kata were under single header, now they are like on different headers for the same kata, so it is possible to doublesolve same kata and get honor twice with this bug.

![image](https://user-images.githubusercontent.com/13510424/57586278-4fbedd80-74fc-11e9-985d-604b7aa1733c.png)
![image](https://user-images.githubusercontent.com/13510424/57586284-65340780-74fc-11e9-9943-4fbb2925d347.png)


Links for Katas:
https://www.codewars.com/kata/5287e858c6b5a9678200083c
https://www.codewars.com/kata/526233aefd4764272800036f

Link to my profile:
https://www.codewars.com/users/AlexPutz

**Comment by AlexPutz** [comment]
Hello.
At least I can consistently reproduce it.

![image](https://user-images.githubusercontent.com/13510424/57808398-f0ff9b00-776b-11e9-9b07-569c6850c352.png)

https://www.codewars.com/kata/perimeter-of-squares-in-a-rectangle/c

**Comment by AlexPutz** [comment]
![image](https://user-images.githubusercontent.com/13510424/57808871-0628f980-776d-11e9-8839-97226c9b0fea.png)
https://www.codewars.com/kata/53da6d8d112bd1a0dc00008b/solutions/c

**Comment by JulianSteinmann** [comment]
![image](https://user-images.githubusercontent.com/35849163/58281497-35f28580-7d9b-11e9-9fdd-9d4e11c1e386.png)
Same here. Tried it twice but can't see the other solutions. In my profile solutions they are duplicated.

**Comment by DonaldKellett** [comment]
Just encountered this issue for the first time with https://www.codewars.com/kata/5d1dd2ba7c046b0023724882/ :

![螢幕截圖 2019-07-04 18 41 43](https://user-images.githubusercontent.com/7777884/60660924-62fe8180-9e8b-11e9-8d95-c6babddc551a.png)

**Comment by hazeycode** [comment]
I'm getting this issue as original reported for solutions in 2 languages for https://www.codewars.com/kata/54b42f9314d9229fd6000d9c

First the C solution submission seemed to time out and meant that the solutions was partially submitted. It also seems like this leaves things in a bad state as the Haskell solution submission resulted in the same issue only without any apparent time out.

**Comment by jtlindsey** [comment]
The issue happen to me for first time today. The page was also loading really slow while all my other sites were loading fast. I reloaded the page and submitted solution again.

**Comment by preactive** [comment]
@kazk without knowing about the data sensitivity nature of the problem... but thought about dropping something like a 1kyu bounties for support in fixing some bugs on the platform like this one?

**Comment by 0legRadchenko** [comment]
![image](https://user-images.githubusercontent.com/32248424/62888294-9fa18080-bd47-11e9-9f47-32f5c2736ff6.png)
I clicked on 'submit solution' and I got an error such as: "You need to complete this task in order to check solutions of other people" then I returned back and submitted my code again and it worked fine but it gave me an extra honor because I repeated this actions 3 times with another submitted solutions (at the third time I have completed this task with more clear code) and then I checked my profile and I have amazed because now I got 100 honors instead of ~30-40 for JUST ONE KATA.

kata - https://www.codewars.com/kata/range-extraction/python
my profile - https://www.codewars.com/users/OlegRadchenko

**Comment by suryasiriki4** [comment]
It is still not rectified in 2019 Aug.Why the hell ,code wars are not resolving this bug.My impression on code wars is lost due to this bug.

**Comment by MP7373** [comment]
I ran into this issue for the first time (the first time I remember) two times in the past week and I just recently got codewars red. Does it have anything to do with codewars red or is it just coincidence and is just there being duplicate projects?

![image](https://user-images.githubusercontent.com/11096661/63069517-263f9480-bee5-11e9-84ce-2500140780f2.png)
![image](https://user-images.githubusercontent.com/11096661/63069527-348db080-bee5-11e9-97c3-0e04739dd68b.png)

**Comment by kazk** [comment]
@MP7373 it's not related to Codewars Red.

**Comment by aliasfoxkde** [comment]
Whatever is going on, the problem initially and randomly would not allow me to see Kata solutions (sometimes old ones and sometimes new ones after completion, even 8 kyu challenges with an access warning). Now it's extended to being all the time, on multiple browsers (regardless of logging in/out again which would resolve the "issue" in the past) and now I get an "Unauthorized" error when trying to leave a comment. I used to use CodeWars daily but now use it rarely, but started up again to complete Kata's with a friend who is learning to code.

![Kata_Bug_Error](https://user-images.githubusercontent.com/14325925/133807494-d491e894-eaac-418c-bf97-eed89f9874e0.png)

**Comment by Blind4Basics** [comment]
@aliasfoxkde what's your CW's username?

**Comment by aliasfoxkde** [comment]
It's aliasfox

**Comment by Blind4Basics** [comment]
Your account have been restricted because evidences of plagiarism have been found (a lot).

**Comment by aliasfoxkde** [comment]
That's interesting because I've solved every Kata first and then have gone back to refactor solutions more cleverly, often more condensed and shorter, which is what CodeWars seems to lend toward (more clever than maintainable code). It doesn't break any rules and being most things are solved the same way, it is also hardly plagiarism . But if that's the system, I guess it is what it is. I also never received a message and still get daily Kata updates. That sounds like a bug to me. Thanks.

**Comment by Blind4Basics** [comment]
> [...]  It doesn't break any rules

Refactoring, no it doesn't. But that's not the reason why your account got restricted.

Sorry, but when looking at your solutions data, it's absolutely obvious you _didn't_ solve the hard kata "on your own" (nothing in 4 kyu or harder). 

>  I also never received a message 

Effectively, that isn't implemented so far. Dunno if that will be done.

The kata updates aren't related to the account restriction, so no bug there.

**Comment by aliasfoxkde** [comment]
I read through the "Code of Conduct" and "Privacy Policy" and I didn't explicitly violate them, but I see looking at your account on GitHub that you did: "Please do not post your solutions on Github.". I do have another account with have more progress, but I digress. I don't mean disrespect, but if you're going to hold someone accountable, hold them (including yourself) to a standard.

You might need a refresher, so here's some reading material:

Links:
https://docs.codewars.com/community/rules/
https://www.codewars.com/about/privacy

**Comment by Blind4Basics** [comment]
> I didn't explicitly violate them

Completing kata using solutions of other users is not "honorable" in any way...

> (including yourself)

'beg you pardon??

**Comment by ZdraviiSmisl** [comment]
May I ask why my account was closed? Username: My_brain_is_gone. I'v lost no opportunity to see other users solutions

**Comment by hobovsky** [comment]
> May I ask why my account was closed? Username: My_brain_is_gone. I'v lost no opportunity to see other users solutions

It was temporarily muted for use of bad language in comments. The lock is not permanent, it will be removed soon.

**Comment by ZdraviiSmisl** [comment]
From now on I'll know that 

> > May I ask why my account was closed? Username: My_brain_is_gone. I'v lost no opportunity to see other users solutions
> 
> It was temporarily muted for use of bad language in comments. The lock is not permanent, it will be removed soon.

From now on I'll know that there are Russian-speaking moderators on CW
