### ISSUE TITLE
Searching problems on basis of topic

### ISSUE THREAD

**Issue by grvkmrpandit** [codewars/codewars.com#2124]
I want to have a search box where I will enter a topic such as segment trees and and get all problems related to it becasuse I do not want to waste my time on solving simple katas that you people suggests.

**Comment by hobovsky** [comment]
You mean something like this?

![image](https://user-images.githubusercontent.com/23709795/81153367-24da5e80-8f83-11ea-816d-66f6306826cf.png)

But the search mechanism used here is far from perfect, if a kata does not mention segment trees in title or description, it won't be found.

**Comment by grvkmrpandit** [comment]
but this seacrh shows only the problems solved by me.I want to know all the problems of the give search key i.e I want to search globaly irrespective of user and the problems I solved.

**Comment by hobovsky** [comment]
Have you tried to refine search options a bit? I marked some options you could try:

![image](https://user-images.githubusercontent.com/23709795/81167110-ea79bd00-8f94-11ea-9335-67f1dc65a0ff.png)

With this example search configuration, it will search for ALL kta, not only the ones you solved, but also the ones you have not solved yet.

But again, there's a lot to improve in how this search works and it might be not enough. People don't always care about putting meaningful stuff in their descriptions, and tags could use some improvements.
