### ISSUE TITLE
HASKELL Bug

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#700]
Haskell katas give now lots of warnings so that guys can't anymore pass them. 

The warnings are about "Tabs" as indentations.
Examples:
```
/tmp/haskell116114-18-1ksd9bb.dy9okwqaor/Codewars/G964/Countdig/Test.hs:11:1: Warning:
    Tab character
```
I corrected the kata:
<https://www.codewars.com/kata/count-the-digit> replacing each tab by spaces but I can't do that for all my Haskell katas. Something must have been changed somewhere!
See @AntoineGagne post: <https://www.codewars.com/kata/count-the-digit/discuss/haskell>

Furthermore when validating before publishing it is impossible to validate separately the "Example Test Cases", all tests are validated. Painful and already said by others.

**Comment by AntoineGagne** [comment]
After searching a bit, I found the following pragma:
```haskell
{-# OPTIONS_GHC -fno-warn-tabs #-}
```
which could fix this warning. You would have to put it in the files with the tabs and it would turn off the warnings. Alternatively, you could put `ghc-options: -fno-warn-tabs` in your `.cabal` files. While it is not a perfect solution, at least, it would be faster than replacing all the tabs with spaces.

Sorry if it does not help!

**Comment by g964** [comment]
Yes in another one I put the pragma ``{-# OPTIONS -w #-}. I will try with the one you said (OPTIONS_GHC is not known in that CW Haskell version). Your pragma is better since less strong... It was faster than replacing tabs with spaces. Lots of thanks!

**Comment by g964** [comment]
Another Haskell kata with tabs problems:

<https://www.codewars.com/kata/559536379512a64472000053/discuss/haskell>

**Comment by matthewmoppett** [comment]
Another way of looking at this problem is that it's impossible to complete the kata -- even if you pass all the tests -- if anything gets printed to stderr. I've encountered this problem with a kata where I was printing stuff to stderr as a debugging tool -- I just removed the debugging stuff, and the kata passed. 

It's more serious with kata like https://www.codewars.com/kata/data-types-a-la-carte, where the set-up of the kata ensures that a warning is printed to stderr. In this case we get stuff like:

 /tmp/haskell116117-18-ikuj3u.b9fm8fflxr/ALaCarte/ExampleTests.hs:1:139: Warning:
    -XOverlappingInstances is deprecated: instead use per-instance pragmas OVERLAPPING/OVERLAPPABLE/OVERLAPS

/tmp/haskell116117-18-ikuj3u.b9fm8fflxr/ALaCarte.hs:1:104: Warning:
    -XOverlappingInstances is deprecated: instead use per-instance pragmas OVERLAPPING/OVERLAPPABLE/OVERLAPS

Which really can't be fixed without fundamentally changing the kata.

This must be a new thing, since lots of people have completed that kata already.

**Comment by g964** [comment]
Seems right, fixed with cabal.config.

**Comment by pcrama** [comment]
Yes, the fix looks right but my solution is still rejected (2016-12-15 12:37 AM CET).

**Comment by g964** [comment]
The problem seemed fixed but it appears again!
yesterday: <https://www.codewars.com/kata/56541980fa08ab47a0000040/discuss/haskell>
today: <https://www.codewars.com/kata/54e320dcebe1e583250008fd/discuss/haskell>

Furthermore: impossible to edit any kata:
```
Looks like there was a server error! (500)
```

**Comment by ice1000** [comment]
This bug still appears, even in the [preview channel](https://preview.codewars.com/kata/data-types-a-la-carte/train/haskell).

```haskell
{-# OPTIONS_GHC -fno-warn-deprecated-flags #-}
{-# OPTIONS_GHC -fno-warn-tabs #-}
```

But I reviewed the opensource sandbox, the issue seems fixed. Why it's still there? Did the code deployed?

**Comment by Voileexperiments** [comment]
Of course... not! :P

But you should be able to edit the kata yourself now (since #1010).

**Comment by kazk** [comment]
Does `runhaskell` respect `~/.cabal/config`?

```js
runCode({
  name: 'runhaskell',
  args: ['-i' + ['frameworks/haskell', haskellCodeDir].join(':'), fixtureFileName],
  options: {env: process.env}
});
```
[lib/runners/haskell.js#L28-L32](https://github.com/Codewars/codewars-runner-cli/blob/77b5db036f4b75460bfb15578c49600be95963ad/lib/runners/haskell.js#L28-L32)

I think we need `runhaskell -- -fno-warn-tabs`?

**Comment by kazk** [comment]
Opened PR to fix this (https://github.com/Codewars/codewars-runner-cli/pull/461)
